import type { ResumeData } from "@/types/resume";
import { createEmptyExperience, createEmptyEducation, createEmptyProject } from "@/types/resume";
import { TEMPLATE_IDS } from "@/types/resume";

const NAMES = [
  "Alex Morgan",
  "Jordan Lee",
  "Sam Rivera",
  "Casey Chen",
  "Riley Kim",
  "Avery Johnson",
  "Quinn Davis",
  "Elliott Brown",
  "Morgan Taylor",
  "Cameron Wilson",
  "Skyler Martinez",
  "Reese Anderson",
  "Drew Thompson",
  "Blake White",
  "Finley Harris",
  "Sage Clark",
  "Parker Lewis",
  "Hayden Walker",
  "Emery Hall",
  "Rowan Young",
  "Eden King",
  "River Wright",
  "Phoenix Scott",
  "Arlo Green",
  "Jasper Adams",
  "Nico Nelson",
  "Kai Mitchell",
  "Leo Roberts",
  "Aria Turner",
  "Luna Phillips",
  "Zoe Campbell",
  "Ivy Parker",
  "Maya Evans",
  "Nora Edwards",
  "Ella Collins",
];

const TITLES = [
  "Senior Software Engineer",
  "Product Manager",
  "Data Analyst",
  "UX Designer",
  "DevOps Engineer",
  "Full Stack Developer",
  "Engineering Manager",
  "Data Scientist",
  "Technical Lead",
  "Solutions Architect",
  "Marketing Director",
  "Financial Analyst",
  "Operations Manager",
  "HR Business Partner",
  "Sales Director",
  "Consultant",
  "Project Manager",
  "Research Scientist",
  "Content Strategist",
  "Growth Lead",
  "Backend Engineer",
  "Frontend Developer",
  "ML Engineer",
  "Security Engineer",
  "Cloud Architect",
  "VP Engineering",
  "CTO",
  "CEO",
  "Founder",
  "Design Lead",
  "Brand Manager",
  "Account Executive",
  "Legal Counsel",
  "Strategy Associate",
  "Business Analyst",
];

const COMPANIES = [
  "Tech Corp",
  "Global Systems Inc",
  "NextGen Labs",
  "Scale Ventures",
  "DataDrive",
  "CloudFirst",
  "Innovate Co",
  "Summit Consulting",
  "Apex Solutions",
  "Vertex Industries",
  "Meridian Group",
  "Pinnacle Tech",
  "Catalyst Labs",
  "Nexus Partners",
  "Horizon Inc",
  "Stellar Dynamics",
  "Prime Analytics",
  "Fusion Systems",
  "Quantum Labs",
  "Atlas Consulting",
  "Beacon Industries",
  "Crest Solutions",
  "Delta Ventures",
  "Echo Technologies",
  "Forge Co",
  "Grid Systems",
  "Helix Partners",
  "Ion Labs",
  "Jade Consulting",
  "Kite Technologies",
  "Lumina Inc",
  "Mosaic Group",
  "Nova Systems",
  "Orbit Ventures",
  "Pulse Analytics",
];

const SCHOOLS = [
  "State University",
  "MIT",
  "Stanford",
  "Berkeley",
  "Carnegie Mellon",
  "Georgia Tech",
  "University of Texas",
  "NYU",
  "Columbia",
  "Northwestern",
  "University of Chicago",
  "Duke",
  "UCLA",
  "USC",
  "Boston University",
  "Penn State",
  "Ohio State",
  "University of Michigan",
  "Purdue",
  "Cornell",
  "Yale",
  "Harvard",
  "Princeton",
  "Brown",
  "Dartmouth",
  "London School of Economics",
  "Imperial College",
  "ETH Zurich",
  "INSEAD",
  "Wharton",
  "Kellogg",
  "Booth",
  "Sloan",
  "Haas",
  "Anderson",
  "Tepper",
];

const DEGREES = [
  "B.S. Computer Science",
  "B.A. Economics",
  "M.S. Data Science",
  "MBA",
  "B.S. Engineering",
  "M.Eng. Software Engineering",
  "Ph.D. Machine Learning",
  "B.S. Statistics",
  "M.S. Information Systems",
  "B.B.A. Finance",
  "M.F.A. Design",
  "B.S. Mathematics",
  "M.S. Analytics",
  "B.A. Communications",
  "LLB",
  "B.S. Electrical Engineering",
  "M.S. Cybersecurity",
  "B.S. Physics",
  "M.P.H.",
  "B.S. Business",
  "M.S. Management",
  "B.A. Psychology",
  "M.S. Human-Computer Interaction",
  "B.S. Biology",
  "M.S. Biotechnology",
  "B.Arch",
  "M.S. Finance",
  "B.S. Accounting",
  "M.S. Marketing",
  "B.A. English",
  "M.S. Operations",
  "B.S. Chemistry",
  "M.S. Chemical Engineering",
  "B.S. Mechanical Engineering",
  "M.S. Industrial Engineering",
];

const BULLETS = [
  "Led cross-functional team of 8 to deliver product on time and under budget.",
  "Increased user engagement by 40% through data-driven A/B testing.",
  "Built and scaled backend services handling 1M+ requests per day.",
  "Reduced infrastructure costs by 25% via migration to serverless.",
  "Designed and implemented CI/CD pipeline cutting release time by 60%.",
  "Drove revenue growth of 15% YoY through new market expansion.",
  "Mentored 5 junior engineers and established best practices.",
  "Collaborated with design to ship award-winning mobile experience.",
  "Presented to C-suite on quarterly strategy and KPIs.",
  "Launched 3 new product lines from concept to market.",
  "Improved NPS by 20 points through customer feedback loops.",
  "Managed P&L of $10M and delivered 12% margin improvement.",
  "Built forecasting models that reduced inventory costs by 18%.",
  "Led due diligence on 4 M&A targets; closed 2 acquisitions.",
  "Implemented security framework achieving SOC 2 compliance.",
  "Redesigned onboarding flow, increasing activation by 35%.",
  "Negotiated partnerships with 5 Fortune 500 companies.",
  "Shipped 12 features in 6 months with 99.9% uptime.",
  "Led diversity initiative; increased underrepresented hires by 25%.",
  "Created content strategy that grew organic traffic 3x.",
  "Automated reporting saving 20 hours per week for finance.",
  "Built real-time dashboards used by 50+ stakeholders.",
  "Reduced churn by 15% through proactive customer success.",
  "Launched API used by 200+ external developers.",
  "Led IPO readiness and roadshow preparation.",
  "Designed compensation framework adopted company-wide.",
  "Drove product-market fit research for new vertical.",
  "Managed $5M budget and delivered 110% of targets.",
  "Implemented agile at scale across 6 teams.",
  "Led technical integration of acquired company.",
  "Built ML pipeline that improved conversion by 22%.",
  "Established design system used across 15 products.",
  "Reduced mean time to resolution by 40%.",
  "Launched international expansion in 3 new markets.",
  "Drove culture and engagement scores to top quartile.",
];

const SUMMARIES = [
  "Detail-oriented engineer with 6+ years turning complex requirements into scalable systems. Passionate about clean architecture and team growth.",
  "Strategic product leader focused on user value and business outcomes. Track record of 0-to-1 products and scaling teams.",
  "Data-driven analyst with expertise in SQL, Python, and visualization. Translates data into actionable insights for exec and product teams.",
  "Human-centered designer with a bias for shipping. Experienced in design systems and cross-functional collaboration.",
  "DevOps and platform engineer with a focus on reliability and developer experience. Strong background in AWS and Kubernetes.",
  "Full stack developer with a passion for performance and accessibility. Shipped products used by millions.",
  "Engineering manager who cares about people and delivery. Built and led teams of 5–15 at high-growth startups.",
  "Data scientist with PhD and industry experience in ML and experimentation. Published and patent-holding.",
  "Technical lead who drives alignment and quality. Experienced in distributed systems and on-call culture.",
  "Solutions architect with 10+ years helping enterprises adopt cloud and modernize applications.",
  "Marketing leader with B2B and B2C experience. Focus on brand, demand gen, and lifecycle marketing.",
  "Finance professional with FP&A and strategic planning background. Supported C-suite on M&A and budgeting.",
  "Operations leader focused on process, tools, and scaling. Improved efficiency and reduced operational risk.",
  "HR business partner with expertise in talent, comp, and org design. Supported 200+ headcount growth.",
  "Sales leader with enterprise and SMB experience. Consistently exceeded quota and built high-performing teams.",
  "Management consultant with strategy and operations experience. Ex-MBB, led 20+ engagements.",
  "Project and program manager with PMP and agile certifications. Delivered $50M+ in programs.",
  "Research scientist with publications in top venues. Bridge between research and product.",
  "Content and brand strategist. Built editorial and social strategy that grew audience 5x.",
  "Growth lead with expertise in acquisition, retention, and monetization. Data-informed experimentation.",
  "Backend engineer specializing in distributed systems and databases. Open source contributor.",
  "Frontend engineer with deep React and design-system experience. Advocate for performance and a11y.",
  "ML engineer who ships models to production. Experience in NLP and recommendation systems.",
  "Security engineer with offensive and defensive background. Led incident response and compliance.",
  "Cloud architect with multi-cloud experience. Designed systems for compliance and scale.",
  "VP Engineering with 15+ years building and scaling engineering orgs. Focus on culture and delivery.",
  "CTO and technical co-founder. Led product and engineering through Series B.",
  "CEO and founder. Scaled company from 0 to 50 and raised Series A.",
  "Design lead who built and evolved design teams and systems. Strong in UX and visual design.",
  "Brand and marketing leader. Built brand from scratch and grew awareness 10x.",
  "Account executive with enterprise sales experience. Consistent top performer.",
  "Legal counsel with tech and commercial experience. Supported fundraising and contracts.",
  "Strategy associate with consulting and corp dev background. Led strategic projects.",
  "Business analyst with expertise in requirements, process, and tooling. Bridge between business and tech.",
  "Analytics and insights lead. Drove data culture and self-serve analytics.",
];

const SKILLS_SETS = [
  ["Python", "SQL", "Power BI", "Excel", "Tableau"],
  ["JavaScript", "React", "Node.js", "TypeScript", "AWS"],
  ["Java", "Spring", "Kafka", "PostgreSQL", "Docker"],
  ["Go", "Kubernetes", "gRPC", "Terraform", "Prometheus"],
  ["C++", "Rust", "Linux", "Systems Design", "Performance"],
  ["Figma", "Sketch", "Prototyping", "User Research", "Design Systems"],
  ["Product Strategy", "Roadmapping", "Stakeholder Management", "Analytics", "A/B Testing"],
  ["Data Modeling", "ETL", "Spark", "Airflow", "dbt"],
  ["ML", "TensorFlow", "PyTorch", "Experimentation", "MLOps"],
  ["Salesforce", "HubSpot", "Demand Gen", "SEO", "Content"],
  ["Financial Modeling", "Excel", "VBA", "Budgeting", "Forecasting"],
  ["Recruiting", "Compensation", "L&D", "HRIS", "Employment Law"],
  ["Negotiation", "Enterprise Sales", "CRM", "Pipeline Management", "Presentations"],
  ["Strategy", "Operations", "Project Management", "Stakeholder Communication"],
  ["Agile", "Jira", "Confluence", "Risk Management", "Vendor Management"],
  ["Research", "Writing", "Statistics", "R", "Python"],
  ["Copywriting", "SEO", "Social Media", "Campaigns", "Analytics"],
  ["Growth", "Experimentation", "SQL", "Amplitude", "Optimization"],
  ["Security", "Penetration Testing", "Compliance", "Incident Response", "IAM"],
  ["GCP", "Azure", "Multi-cloud", "Cost Optimization", "Architecture"],
  ["Leadership", "Hiring", "Performance", "Strategy", "Board Reporting"],
  ["Fundraising", "Investor Relations", "P&L", "Strategy", "Team Building"],
  ["Design Leadership", "Hiring", "Design Ops", "Research", "Figma"],
  ["Brand Strategy", "Campaigns", "Partnerships", "Analytics", "Team Leadership"],
  ["Discovery", "Objection Handling", "Closing", "Forecasting", "Coaching"],
  ["Contracts", "Compliance", "IP", "Negotiation", "Corporate Governance"],
  ["Due Diligence", "Modeling", "Presentation", "Stakeholder Management", "Research"],
  ["Requirements", "Process Design", "Jira", "SQL", "Stakeholder Management"],
  ["SQL", "Python", "Looker", "A/B Testing", "Statistics"],
  ["Communication", "Writing", "Editing", "Strategy", "Team Collaboration"],
  ["Excel", "PowerPoint", "Financial Analysis", "Variance Analysis", "Reporting"],
  ["Recruiting", "Interviewing", "Employer Brand", "DEI", "Analytics"],
  ["Enterprise Sales", "Solution Selling", "Discovery", "Negotiation", "Account Planning"],
  ["Legal Research", "Drafting", "Compliance", "Risk", "Corporate"],
  ["Strategy", "Analysis", "Frameworks", "Executive Communication", "Project Management"],
  ["Requirements", "Process Improvement", "Data Analysis", "Stakeholder Management", "Documentation"],
];

const PROJECTS = [
  { title: "Forecasting Model", desc: "Built time-series model to reduce inventory costs by 15%." },
  { title: "API Platform", desc: "Designed and launched internal API used by 20+ teams." },
  { title: "Design System", desc: "Led creation of component library adopted across 10 products." },
  { title: "Migration to Cloud", desc: "Led migration of 50+ services to AWS; reduced cost 30%." },
  { title: "Recommendation Engine", desc: "Shipped ML model that improved CTR by 25%." },
  { title: "Customer Portal", desc: "Built self-serve portal reducing support tickets by 40%." },
  { title: "Compliance Program", desc: "Implemented program that achieved SOC 2 in 6 months." },
  { title: "Pricing Optimization", desc: "Data model that increased revenue per user by 12%." },
  { title: "Mobile App v2", desc: "Shipped redesign; app store rating improved from 3.8 to 4.6." },
  { title: "Real-time Dashboard", desc: "Built dashboard used by exec team for weekly reviews." },
  { title: "Acquisition Integration", desc: "Led technical integration of acquired company; 90-day timeline." },
  { title: "Diversity Initiative", desc: "Program that increased underrepresented hiring by 25%." },
  { title: "Content Engine", desc: "CMS and workflow that 3x'd content output." },
  { title: "Churn Prediction", desc: "ML model identifying at-risk accounts; reduced churn 15%." },
  { title: "Developer Portal", desc: "Documentation and sandbox for 200+ external developers." },
  { title: "IPO Readiness", desc: "Led controls, reporting, and audit prep for public offering." },
  { title: "Comp Framework", desc: "Designed leveling and comp structure adopted company-wide." },
  { title: "New Market Entry", desc: "Research and GTM plan for expansion into 3 new countries." },
  { title: "Budget System", desc: "Tooling that reduced budget cycle time by 50%." },
  { title: "Agile at Scale", desc: "Rolled out SAFe across 6 teams; delivery predictability improved." },
  { title: "Security Audit", desc: "Led penetration test and remediation; zero critical findings at sign-off." },
  { title: "Cost Optimization", desc: "Right-sized resources; cloud spend down 28% YoY." },
  { title: "Engagement Survey", desc: "Designed and ran survey; action plans in 5 key areas." },
  { title: "Brand Refresh", desc: "Rebrand and guidelines; NPS and awareness both up." },
  { title: "Enterprise Deal", desc: "Closed $2M ARR deal with Fortune 100; 9-month cycle." },
  { title: "Contract Automation", desc: "Templates and workflow; legal review time down 40%." },
  { title: "Strategic Plan", desc: "Led 3-year strategy and board presentation." },
  { title: "Requirements Library", desc: "Centralized backlog and process; clarity and velocity improved." },
  { title: "Self-Serve Analytics", desc: "Trained 100+ users; reduced ad-hoc report requests 60%." },
  { title: "Editorial Calendar", desc: "Process and tooling for content planning and production." },
  { title: "Forecast Accuracy", desc: "New models improved forecast accuracy by 20%." },
  { title: "Talent Pipeline", desc: "Built pipeline that cut time-to-fill by 25%." },
  { title: "Territory Plan", desc: "Redesigned territories; quota attainment up 15%." },
  { title: "IP Strategy", desc: "Patent strategy and filings in 3 key areas." },
  { title: "Market Analysis", desc: "TAM/SAM/SOM and competitive analysis for new product." },
  { title: "Process Mapping", desc: "Mapped and improved order-to-cash; cycle time down 30%." },
];

function hash(s: string): number {
  let h = 0;
  for (let i = 0; i < s.length; i++) h = ((h << 5) - h + s.charCodeAt(i)) | 0;
  return Math.abs(h);
}

function pick<T>(arr: T[], seed: number): T {
  return arr[seed % arr.length];
}

/**
 * Returns different sample resume data per template so each of the 35 templates
 * shows unique content in previews (different names, roles, companies, etc.).
 */
export function getSampleResumeData(templateId: ResumeData["templateId"]): ResumeData {
  const idx = TEMPLATE_IDS.indexOf(templateId);
  const seed = idx >= 0 ? hash(templateId + String(idx)) : 0;
  const s = (n: number) => (seed + n) >>> 0;

  const name = pick(NAMES, s(0));
  const title = pick(TITLES, s(1));
  const company = pick(COMPANIES, s(2));
  const school = pick(SCHOOLS, s(3));
  const degree = pick(DEGREES, s(4));
  const summary = pick(SUMMARIES, s(5));
  const skills = pick(SKILLS_SETS, s(6));
  const project = pick(PROJECTS, s(7));
  const bullets = [pick(BULLETS, s(8)), pick(BULLETS, s(9))];

  return {
    templateId,
    personal: {
      fullName: name,
      email: `${name.split(" ")[0].toLowerCase()}@example.com`,
      phone: "+1 555 000 0000",
      location: "San Francisco, CA",
      linkedin: `linkedin.com/in/${name.split(" ")[0].toLowerCase()}`,
      website: `${name.split(" ")[0].toLowerCase()}.dev`,
      title,
    },
    summary,
    experience: [
      {
        ...createEmptyExperience("sample-exp-1"),
        jobTitle: title,
        company,
        location: "Remote",
        startDate: "2020",
        endDate: "Present",
        current: true,
        bullets,
      },
    ],
    education: [
      {
        ...createEmptyEducation("sample-edu-1"),
        school,
        degree,
        field: "Relevant Field",
        startDate: "2014",
        endDate: "2018",
        gpa: "3.8",
      },
    ],
    skills,
    certifications: [],
    projects: [
      {
        ...createEmptyProject("sample-proj-1"),
        title: project.title,
        description: project.desc,
      },
    ],
  };
}
