import React from "react";
import type { ResumeData } from "@/types/resume";

export interface AddonResult {
  slug: string;
  title: string;
  content: string;
}

interface AddonsDocumentProps {
  data: ResumeData;
  addons: AddonResult[];
}

export function AddonsDocument({ data, addons }: AddonsDocumentProps) {
  if (!addons || addons.length === 0) {
    return null;
  }

  // Use a simple, clean, and professional design suitable for a standard A4 PDF.
  // Using Tailwind typography but keeping it simple to ensure `html2canvas` prints it correctly.
  
  return (
    <div className="bg-white p-12 mx-auto" style={{ width: "21cm", minHeight: "29.7cm", color: "#1c1917" }}>
      {/* Header section matching resume style roughly */}
      <div className="border-b-2 border-stone-200 pb-6 mb-8 text-center">
        <h1 className="text-3xl font-black text-stone-900 tracking-tight uppercase mb-2">
          {data.personal?.fullName || "Your Placement"} Add-ons
        </h1>
        <p className="text-stone-500 text-sm font-medium tracking-wide">
          Customized for {data.personal?.title || "your target role"}
        </p>
      </div>

      <div className="space-y-12">
        {addons.map((addon, index) => (
          <div key={addon.slug} className={`break-inside-avoid shadow-sm rounded-xl border border-stone-200 p-6 ${index > 0 ? "page-break-before" : ""}`}>
            <h2 className="text-xl font-bold text-amber-700 mb-4 pb-2 border-b border-stone-100 flex items-center gap-2">
              <span className="w-8 h-8 rounded-lg bg-amber-50 text-amber-600 flex items-center justify-center text-sm shadow-sm border border-amber-100">
                {index + 1}
              </span>
              {addon.title}
            </h2>
            
            <div className="prose prose-sm prose-stone max-w-none">
              {/* Parse the Markdown-lite content coming from Mistral */}
              {addon.content.split("\\n").map((paragraph, i) => {
                const text = paragraph.trim();
                if (!text) return null;
                
                // Super basic markdown parsing for bold and lists
                if (text.startsWith("- ") || text.startsWith("* ")) {
                  return <li key={i} className="ml-4 mb-2">{formatBold(text.substring(2))}</li>;
                }
                if (/^\\d+\\.\\s/.test(text)) {
                  return <li key={i} className="ml-4 mb-2 list-decimal">{formatBold(text.replace(/^\\d+\\.\\s/, ""))}</li>;
                }
                if (text.startsWith("### ")) {
                  return <h4 key={i} className="text-base font-bold text-stone-800 mt-4 mb-2">{formatBold(text.substring(4))}</h4>;
                }
                if (text.startsWith("## ")) {
                  return <h3 key={i} className="text-lg font-bold text-stone-800 mt-6 mb-3">{formatBold(text.substring(3))}</h3>;
                }
                
                return <p key={i} className="mb-4 leading-relaxed text-stone-700">{formatBold(text)}</p>;
              })}
            </div>
          </div>
        ))}
      </div>
      
      {/* Footer */}
      <div className="mt-16 pt-8 border-t border-stone-200 text-center text-xs text-stone-400">
        Generated by SamosaCV AI &bull; {new Date().toLocaleDateString()}
      </div>
    </div>
  );
}

function formatBold(text: string) {
  // Replace **text** with <strong>text</strong>
  const parts = text.split(/\\*\\*(.*?)\\*\\*/g);
  return parts.map((part, i) => 
    i % 2 === 1 ? <strong key={i} className="font-bold text-stone-900">{part}</strong> : part
  );
}
